[package]
name = "rust-project"
version = "0.1.0"
authors = ["@NAME <@EMAIL>"]
edition = "2018"

[dependencies]
actix-web = "1.0.8"
lazy_static = "1.4.0"
diesel = { version = "1.4.3", features = ["sqlite"] }
